### ISSUE TITLE
Tired of this "Error: Missing REDDIT_USERNAME environment variable"

### ISSUE THREAD

**Issue by wewew12345** [Massolari/reddit_to_telegram#4] opened 2024-03-23 01:40 UTC
I've tried both the methods but still get the same error again and again. I'm no pro. I'm still learning and I faced so many different errors and somehow solved every one of them but this is really disappointing to me. I've spent so much time trying to get it running but it keeps popping that error no matter what method I try. Please help me set it up. Now after all my efforts, I'm almost at the point of giving up.

**Comment by Massolari** [comment] 2024-03-26 09:11
Hey! Don't worry, it's probably a detail that is missing on your setup.
Could you give more information about how is your setup? Which files you created and how are you running the script?

**Comment by Imsleepyyy** [comment] 2024-04-02 10:57
Hey, I tried once again with docker and I did exactly how you told me to. Followed the exact steps, that is, set up .env and bridges.json file, added the bot as admin in the channel and did docker run, as you told me to.

I tried it on a clean vps. I only had updated my packaged and had docker installed prior to trying to deploy the bot and had done nothing else. Take a look at this for the commands I ran - [link](https://binshare.net/5VoMZXRqyTfhhZHRG7aK)

I only created two files. First is .env file and second is bridges.json and the db folder was created automatically. 

Here is how my .env file looks like -

#Your Reddit username and password
REDDIT_USERNAME=Interesting_Car6054
REDDIT_PASSWORD=abc
#Reddit client ID and secret
#You can get these by creating an app on https://www.reddit.com/prefs/apps
REDDIT_CLIENT_ID=abc
REDDIT_CLIENT_SECRET=abc
#Telegram bot token
#You can get this by creating a bot with @BotFather
TELEGRAM_TOKEN=abc

I'm the same guy above. This is my alt account.

**Comment by Massolari** [comment] 2024-04-02 11:59
I could reproduce it and already pushed a commit adding a note in the README.

The issue is that the `.env` file can't contain comments (lines that begin with `#`).
So you just need to remove those lines and only keep the lines:
```
REDDIT_USERNAME=Interesting_Car6054
REDDIT_PASSWORD=abc
REDDIT_CLIENT_ID=abc
REDDIT_CLIENT_SECRET=abc
TELEGRAM_TOKEN=abc
```

Thanks for helping me find this behavior

**Comment by Massolari** [comment] 2024-04-02 12:55
Let me know if that works so we can close this issue

**Comment by Imsleepyyy** [comment] 2024-04-02 16:04
> Let me know if that works so we can close this issue

Thanks! It got past that!
But now I have some other error :(
Here it is -
[image](https://files.catbox.moe/ui59gu.png)

And I have the same set up as last time. The only change this time around is that I have removed the comments in .env file and rebuilt the image and container from scratch.

Edit - It gave off the same "Couldn't decode bridges" error when I first tried it with the previous image and container. The reason why I destroyed the previous image and container was to try with a fresh set up and see if I get it again That's all.

**Comment by Imsleepyyy** [comment] 2024-04-02 16:24
And I have checked and verified that all the details in .env file and bridges.json file are correct and even checked that bot is admin of that telegram channel. If it comes to it, I can even share the .env file too.

**Comment by Massolari** [comment] 2024-04-02 16:45
Could you paste your `bridges.json` content here? JSON is a strict format and anything "out of the rules" can make it break

**Comment by Massolari** [comment] 2024-04-02 16:49
Ok, I already have a clue.
In the README the `bridges.json` example contains a trailing comma after the `}`:
```json
[
  {
    "subreddit": "gleamlang",
    "reddit_sort": "hot",
    "telegram_channel": "@r_gleam"
  },
]
```

This is not allowed, the correct is:
```json
[
  {
    "subreddit": "gleamlang",
    "reddit_sort": "hot",
    "telegram_channel": "@r_gleam"
  }
]
```

I just pushed a commit to fix this mistake in the documentation.

Thanks again!
I hope you can make it work now

**Comment by Imsleepyyy** [comment] 2024-04-02 17:24
When I first saw your 1st reply, I had no way to get the bridges.json file out of my vps so I tried setting up rclone and sending the bridges.json file and when I came to send it over, I saw your other reply, lol.

And yes, that did it!! I got past that and then I met with another error xD

But this time around it told me where I went wrong i.e. I had to change my app from "web app" to "script app". So I did that and tried it again with a fresh new "script app" and yes, it did send reddit posts to my channel!!! 
(think you should mention this in README file. Would help other people like me, lol) 

I'm feeling very happy right now, lol. Thank you so much for this!!!

**Comment by Massolari** [comment] 2024-04-03 07:05
Happy to hear that you got this working 🎉
I'll close the issue, but where did you set this "script app"? Was it in your host provider?

**Closed as completed by Massolari** 2024-04-03 07:05 UTC

**Comment by Imsleepyyy** [comment] 2024-04-03 10:07
> Happy to hear that you got this working 🎉 I'll close the issue, but where did you set this "script app"? Was it in your host provider?

![Screenshot_20240403153121](https://github.com/Massolari/reddit_to_telegram/assets/86151641/224e2894-746c-4eac-8f4d-d88e58f6d70f)

On https://www.reddit.com/prefs/apps

There's web app, installed app and script. First I had it on default, that is, web app. It didn't work, gave off a error telling me that it needs to be script to utilize password or something like that. So I went and deleted that app, created new one and this time around made sure to select script instead of web app and changed client ID and secret to the new app's and it worked this time!!!  🎉

**Comment by Massolari** [comment] 2024-04-03 10:20
Thanks! I'll add this information on the README
